# Generated by Django 4.2.14 on 2025-10-29 18:32

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.CharField(max_length=50)),
                ('incoming_number', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('secret_level', models.CharField(choices=[('normal', 'عادي'), ('secret', 'سري'), ('topsecret', 'سري جدًا')], default='normal', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('margin', models.TextField(blank=True)),
                ('final_status', models.CharField(choices=[('pending', 'قيد الإنهاء'), ('done', 'منجز'), ('hold', 'معلّق')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('etype', models.CharField(choices=[('issuer', 'مصدّرة'), ('receiver', 'مستلمة'), ('both', 'كلاهما')], default='both', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.book')),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='issuing_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_books', to='core.entity'),
        ),
        migrations.AddField(
            model_name='book',
            name='receiving_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_books', to='core.entity'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.book_attachment_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.book')),
            ],
        ),
    ]
