# Generated by Django 4.2.14 on 2025-11-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entity_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='code',
        ),
        migrations.AlterField(
            model_name='book',
            name='final_status',
            field=models.CharField(choices=[('pending', 'قيد المتابعة'), ('done', 'مغلق'), ('hold', 'معلق')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='kind',
            field=models.CharField(choices=[('incoming', 'وارد'), ('outgoing', 'صادر')], default='incoming', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='secret_level',
            field=models.CharField(choices=[('normal', 'اعتيادي'), ('secret', 'سري'), ('topsecret', 'سري للغاية')], default='normal', max_length=10),
        ),
    ]
