# Generated by Django 4.2.14 on 2025-11-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_entity_code_alter_book_final_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='final_status',
            field=models.CharField(choices=[('pending', 'قيد المتابعة'), ('done', 'منجزة'), ('hold', 'معلقة')], default='pending', max_length=10),
        ),
    ]
