# Generated by Django 4.2.14 on 2025-11-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_entity_code_alter_book_final_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
