# Generated by Django 4.2.14 on 2025-12-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpassword',
            old_name='password',
            new_name='password_hash',
        ),
    ]
