# Generated by Django 4.2.14 on 2026-01-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_password_userpassword_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhistory',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='core.attachment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.attachment'),
        ),
    ]
