# Generated by Django 4.2.14 on 2026-01-25 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_extractioncache_alter_aiintegrationsettings_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم Dataset', max_length=200)),
                ('dataset_type', models.CharField(choices=[('feedback', 'من التصحيحات اليدوية'), ('archive', 'من الأرشيف القديم'), ('synthetic', 'بيانات مولدة')], default='feedback', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('processing', 'قيد المعالجة'), ('ready', 'جاهز'), ('used', 'مستخدم في التدريب')], default='pending', max_length=20)),
                ('total_samples', models.IntegerField(default=0, help_text='عدد العينات')),
                ('arabic_samples', models.IntegerField(default=0, help_text='عينات عربية')),
                ('english_samples', models.IntegerField(default=0, help_text='عينات إنجليزية')),
                ('data_file', models.FileField(blank=True, null=True, upload_to='training_datasets/')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='معلومات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dataset تدريب',
                'verbose_name_plural': 'Datasets التدريب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='رقم الإصدار', max_length=50, unique=True)),
                ('base_model', models.CharField(default='easyocr', help_text='النموذج الأساسي', max_length=100)),
                ('training_samples', models.IntegerField(default=0)),
                ('training_duration', models.DurationField(blank=True, null=True)),
                ('avg_confidence', models.FloatField(default=0.0, help_text='متوسط الثقة')),
                ('accuracy_arabic', models.FloatField(default=0.0, help_text='دقة العربية')),
                ('accuracy_english', models.FloatField(default=0.0, help_text='دقة الإنجليزية')),
                ('is_active', models.BooleanField(default=False, help_text='النموذج النشط حالياً؟')),
                ('is_production', models.BooleanField(default=False, help_text='جاهز للإنتاج؟')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ocr_models/')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_on_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to='core.trainingdataset')),
            ],
            options={
                'verbose_name': 'إصدار نموذج OCR',
                'verbose_name_plural': 'إصدارات نماذج OCR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(help_text='مسار الصورة الأصلية', max_length=500)),
                ('original_text', models.TextField(help_text='النص المستخرج من OCR')),
                ('corrected_text', models.TextField(help_text='النص المصحح يدوياً')),
                ('language', models.CharField(choices=[('ar', 'عربي'), ('en', 'إنجليزي'), ('mixed', 'مختلط')], default='ar', max_length=10)),
                ('original_confidence', models.FloatField(default=0.0, help_text='ثقة OCR الأصلية')),
                ('correction_type', models.CharField(choices=[('minor', 'تصحيح بسيط'), ('moderate', 'تصحيح متوسط'), ('major', 'تصحيح كبير')], default='minor', max_length=50)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('used_for_training', models.BooleanField(default=False, help_text='هل تم استخدامه في التدريب؟')),
                ('training_date', models.DateTimeField(blank=True, null=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تصحيح OCR',
                'verbose_name_plural': 'تصحيحات OCR',
                'ordering': ['-corrected_at'],
                'indexes': [models.Index(fields=['used_for_training', 'language'], name='core_ocrfee_used_fo_ed97f7_idx'), models.Index(fields=['corrected_at'], name='core_ocrfee_correct_d7be8a_idx')],
            },
        ),
    ]
