# Generated by Django 4.2.14 on 2026-01-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_trainingdataset_ocrmodelversion_ocrfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='incoming_number',
        ),
        migrations.AddField(
            model_name='book',
            name='outgoing_incoming_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
