# Generated by Django 4.2.14 on 2026-01-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bookcomment'),
        ('core', '0012_attachment_deleted_at_attachment_deleted_by_and_more'),
    ]

    operations = [
    ]
