# Generated by Django 6.0 on 2026-01-28 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_book_incoming_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_deleted', 'created_by', '-date'], name='book_list_main_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_deleted', 'kind', 'final_status'], name='book_filters_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['book_number'], name='book_number_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['outgoing_incoming_number'], name='outgoing_incoming_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='title_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['due_date', 'final_status'], name='due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_by', 'is_deleted'], name='user_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['name'], name='core_entity_name_43cfc9_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['code'], name='core_entity_code_fde2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['is_active', 'name'], name='core_entity_is_acti_93aa9c_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['is_active', 'code'], name='core_entity_is_acti_12727c_idx'),
        ),
    ]
