# Generated by Django 4.2.14 on 2026-04-13 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_entity_options_book_book_list_main_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-date'], 'verbose_name': 'كتاب', 'verbose_name_plural': 'الكتب'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'جهة', 'verbose_name_plural': 'الجهات'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.book'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['book', 'is_deleted'], name='core_attach_book_id_8282b1_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['-uploaded_at'], name='core_attach_uploade_111612_idx'),
        ),
        migrations.AddIndex(
            model_name='bookhistory',
            index=models.Index(fields=['book', '-created_at'], name='core_bookhi_book_id_88629c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookhistory',
            index=models.Index(fields=['action'], name='core_bookhi_action_beaf6f_idx'),
        ),
    ]
