# Generated by Django 4.2.14 on 2026-01-20 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_merge_20260120_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('merge', 'دمج ملفات'), ('delete', 'حذف ملف'), ('upload', 'رفع ملف'), ('restore', 'استعادة نسخة')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'نجح'), ('failed', 'فشل'), ('pending', 'قيد التنفيذ')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='attachmentversion',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachmentversion',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachmentversion',
            name='merge_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attachmentversion',
            name='merge_type',
            field=models.CharField(choices=[('none', 'بدون دمج'), ('pdf', 'دمج PDF'), ('image', 'دمج صور'), ('mixed', 'دمج مختلط')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='attachmentversion',
            name='merged_from_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_to', to='core.attachmentversion'),
        ),
        migrations.AddField(
            model_name='attachmentversion',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='attachmentversion',
            index=models.Index(fields=['attachment', '-version_number'], name='core_attach_attachm_394119_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentversion',
            index=models.Index(fields=['is_merged', 'created_at'], name='core_attach_is_merg_8c71f0_idx'),
        ),
        migrations.AddField(
            model_name='mergelog',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_logs', to='core.attachment'),
        ),
        migrations.AddField(
            model_name='mergelog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mergelog',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_source', to='core.attachmentversion'),
        ),
        migrations.AddField(
            model_name='mergelog',
            name='target_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_target', to='core.attachmentversion'),
        ),
        migrations.AddIndex(
            model_name='mergelog',
            index=models.Index(fields=['attachment', '-performed_at'], name='core_mergel_attachm_332a96_idx'),
        ),
        migrations.AddIndex(
            model_name='mergelog',
            index=models.Index(fields=['action', 'status'], name='core_mergel_action_455276_idx'),
        ),
    ]
