# Generated by Django 4.2.14 on 2026-04-13 09:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_book_options_alter_entity_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='book_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='outgoing_incoming_idx',
        ),
        migrations.AddField(
            model_name='book',
            name='issuing_entities',
            field=models.ManyToManyField(blank=True, related_name='issued_books', to='core.entity', verbose_name='الجهات المصدرة'),
        ),
        migrations.AddField(
            model_name='book',
            name='needs_followup',
            field=models.BooleanField(default=False, verbose_name='يحتاج متابعة'),
        ),
        migrations.AddField(
            model_name='book',
            name='our_number',
            field=models.CharField(default='', max_length=50, verbose_name='رقمنا (صادر/وارد)'),
        ),
        migrations.AddField(
            model_name='book',
            name='receiving_entities',
            field=models.ManyToManyField(blank=True, related_name='received_books', to='core.entity', verbose_name='الجهات المستلمة'),
        ),
        migrations.AddField(
            model_name='book',
            name='sender_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الجهة المصدرة'),
        ),
        migrations.AddField(
            model_name='book',
            name='sender_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='رقم صادر الجهة'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخنا'),
        ),
        migrations.AlterField(
            model_name='book',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المتابعة'),
        ),
        migrations.AlterField(
            model_name='book',
            name='final_status',
            field=models.CharField(choices=[('archived', 'مؤرشف'), ('pending', 'قيد المتابعة'), ('done', 'منجزة'), ('hold', 'معلقة')], default='archived', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='issuing_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_books_legacy', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='book',
            name='kind',
            field=models.CharField(choices=[('outgoing_internal', 'صادر داخلي'), ('outgoing_external', 'صادر خارجي'), ('incoming_internal', 'وارد داخلي'), ('incoming_external', 'وارد خارجي')], default='incoming_internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='margin',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='outgoing_incoming_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='receiving_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_books_legacy', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300, verbose_name='العنوان'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['our_number'], name='our_number_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['sender_number'], name='sender_number_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['needs_followup', 'is_overdue'], name='followup_idx'),
        ),
    ]
