# Generated by Django 4.2.14 on 2026-01-22 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_mergelog_attachmentversion_file_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('extracted', 'مستخرج'), ('reviewed', 'تم المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('book_number', models.CharField(blank=True, max_length=50, null=True)),
                ('book_number_confidence', models.FloatField(default=0.0)),
                ('book_date', models.DateField(blank=True, null=True)),
                ('book_date_confidence', models.FloatField(default=0.0)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('title_confidence', models.FloatField(default=0.0)),
                ('margin_text', models.TextField(blank=True, null=True)),
                ('margin_confidence', models.FloatField(default=0.0)),
                ('secret_level', models.CharField(blank=True, choices=[('normal', 'اعتيادي'), ('secret', 'سري'), ('topsecret', 'سري للغاية')], max_length=20, null=True)),
                ('secret_level_confidence', models.FloatField(default=0.0)),
                ('book_kind', models.CharField(blank=True, choices=[('incoming', 'وارد'), ('outgoing', 'صادر')], max_length=20, null=True)),
                ('book_kind_confidence', models.FloatField(default=0.0)),
                ('issuing_entity_candidates', models.JSONField(default=list)),
                ('receiving_entity_candidates', models.JSONField(default=list)),
                ('issuing_entity_id', models.IntegerField(blank=True, null=True)),
                ('receiving_entity_id', models.IntegerField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extractions', to=settings.AUTH_USER_MODEL)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_extraction', to='core.attachment')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='core.book')),
            ],
            options={
                'verbose_name': 'نتيجة استخراج البيانات',
                'verbose_name_plural': 'نتائج استخراج البيانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('manual_review', 'تحت المراجعة')], default='pending', max_length=20)),
                ('raw_text', models.TextField(blank=True, help_text='النص الخام من OCR', null=True)),
                ('cleaned_text', models.TextField(blank=True, help_text='النص المنظف والمصحح', null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='ثقة OCR (0-100)')),
                ('processing_time', models.FloatField(default=0.0, help_text='وقت المعالجة بالثواني')),
                ('language', models.CharField(default='ar', help_text='اللغة المكتشفة', max_length=50)),
                ('num_characters', models.IntegerField(default=0, help_text='عدد الأحرف المستخرجة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='easyocr', help_text='محرك OCR المستخدم', max_length=100)),
                ('error_message', models.TextField(blank=True, help_text='رسالة الخطأ إن وجدت', null=True)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='core.attachment')),
            ],
            options={
                'verbose_name': 'نتيجة OCR',
                'verbose_name_plural': 'نتائج OCR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('feedback_type', models.CharField(choices=[('correct', 'صحيح'), ('incorrect', 'خاطئ'), ('partial', 'جزئي')], max_length=20)),
                ('original_value', models.TextField()),
                ('corrected_value', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.dataextractionresult')),
            ],
            options={
                'verbose_name': 'ملاحظة الاستخراج',
                'verbose_name_plural': 'ملاحظات الاستخراج',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dataextractionresult',
            name='ocr_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='core.ocrresult'),
        ),
        migrations.AddField(
            model_name='dataextractionresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_extractions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='معرف الجلسة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('log_type', models.CharField(choices=[('EVENT', 'حدث'), ('ERROR', 'خطأ'), ('METRIC', 'قياس')], max_length=20, verbose_name='النوع')),
                ('event_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الحدث')),
                ('data', models.JSONField(default=dict, verbose_name='البيانات')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='الرابط')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
            ],
            options={
                'verbose_name': 'سجل عميل',
                'verbose_name_plural': 'سجلات العملاء',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_client_timesta_0ca361_idx'), models.Index(fields=['session_id', '-timestamp'], name='core_client_session_484c58_idx'), models.Index(fields=['log_type', '-timestamp'], name='core_client_log_typ_9e5ca2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_BOOK', 'إنشاء كتاب'), ('EDIT_BOOK', 'تعديل كتاب'), ('DELETE_BOOK', 'حذف كتاب'), ('EXPORT_DATA', 'تصدير بيانات'), ('BACKUP_DATA', 'نسخ احتياطي'), ('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('SEARCH', 'بحث'), ('SCANNER', 'استخدام السكانر')], max_length=50, verbose_name='الإجراء')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='المسار')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='الطريقة')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='رمز الحالة')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط مستخدم',
                'verbose_name_plural': 'سجلات أنشطة المستخدمين',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_userac_timesta_646400_idx'), models.Index(fields=['user', '-timestamp'], name='core_userac_user_id_c382a9_idx'), models.Index(fields=['action', '-timestamp'], name='core_userac_action_8b7099_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('path', models.CharField(max_length=500, verbose_name='المسار')),
                ('method', models.CharField(max_length=10, verbose_name='الطريقة')),
                ('duration_ms', models.FloatField(verbose_name='المدة (ملي ثانية)')),
                ('db_queries', models.IntegerField(verbose_name='عدد استعلامات قاعدة البيانات')),
                ('status_code', models.IntegerField(verbose_name='رمز الحالة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل أداء',
                'verbose_name_plural': 'سجلات الأداء',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_perfor_timesta_756b0b_idx'), models.Index(fields=['-duration_ms'], name='core_perfor_duratio_34f002_idx'), models.Index(fields=['path', '-timestamp'], name='core_perfor_path_fe6d50_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('severity', models.CharField(choices=[('INFO', 'معلومة'), ('WARNING', 'تحذير'), ('ERROR', 'خطأ'), ('CRITICAL', 'خطير')], max_length=20, verbose_name='الخطورة')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='رمز الخطأ')),
                ('error_type', models.CharField(max_length=100, verbose_name='نوع الخطأ')),
                ('error_message', models.TextField(verbose_name='رسالة الخطأ')),
                ('stack_trace', models.TextField(blank=True, verbose_name='Stack Trace')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='المسار')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل خطأ',
                'verbose_name_plural': 'سجلات الأخطاء',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_errorl_timesta_f18e39_idx'), models.Index(fields=['severity', '-timestamp'], name='core_errorl_severit_154bad_idx'), models.Index(fields=['is_resolved', '-timestamp'], name='core_errorl_is_reso_0eb5c5_idx')],
            },
        ),
    ]
