# Generated by Django 4.2.14 on 2026-04-13 09:30

from django.db import migrations


def migrate_book_data_forward(apps, schema_editor):
    """Copy old field data to new fields and convert kind values."""
    Book = apps.get_model('core', 'Book')

    for book in Book.objects.all():
        changed = False

        # Copy book_number → our_number
        if book.book_number and not book.our_number:
            book.our_number = book.book_number
            changed = True

        # Copy outgoing_incoming_number → sender_number
        if book.outgoing_incoming_number and not book.sender_number:
            book.sender_number = book.outgoing_incoming_number
            changed = True

        # Convert 2-type kind to 4-type (default to internal)
        if book.kind == 'incoming':
            book.kind = 'incoming_internal'
            changed = True
        elif book.kind == 'outgoing':
            book.kind = 'outgoing_internal'
            changed = True

        # Set needs_followup based on old final_status
        if book.final_status in ('pending', 'hold'):
            book.needs_followup = True
            changed = True
        elif book.final_status == 'done':
            book.needs_followup = False
            changed = True
        else:
            # unknown status → archive with no followup
            book.final_status = 'archived'
            book.needs_followup = False
            changed = True

        if changed:
            book.save()

    # Copy FK entities → M2M
    for book in Book.objects.select_related('issuing_entity', 'receiving_entity').all():
        if book.issuing_entity_id:
            book.issuing_entities.add(book.issuing_entity_id)
        if book.receiving_entity_id:
            book.receiving_entities.add(book.receiving_entity_id)


def migrate_book_data_backward(apps, schema_editor):
    """Reverse: copy M2M back to FK and revert kind values."""
    Book = apps.get_model('core', 'Book')

    for book in Book.objects.all():
        # Revert kind
        if book.kind.startswith('incoming'):
            book.kind = 'incoming'
        elif book.kind.startswith('outgoing'):
            book.kind = 'outgoing'

        # Copy our_number → book_number
        if book.our_number and not book.book_number:
            book.book_number = book.our_number

        # Copy sender_number → outgoing_incoming_number
        if book.sender_number and not book.outgoing_incoming_number:
            book.outgoing_incoming_number = book.sender_number

        book.save()

    # Copy first M2M entity back to FK
    for book in Book.objects.prefetch_related('issuing_entities', 'receiving_entities').all():
        issuing = book.issuing_entities.first()
        receiving = book.receiving_entities.first()
        if issuing:
            book.issuing_entity = issuing
        if receiving:
            book.receiving_entity = receiving
        book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_book_restructure_phase1'),
    ]

    operations = [
        migrations.RunPython(migrate_book_data_forward, migrate_book_data_backward),
    ]
