# Generated by Django 4.2.14 on 2026-01-22 09:35
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dataextractionresult_ocrresult_extractionfeedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_images_processed', models.IntegerField(default=0)),
                ('successful_extractions', models.IntegerField(default=0)),
                ('failed_extractions', models.IntegerField(default=0)),
                ('manual_review_required', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('median_confidence', models.FloatField(default=0.0)),
                ('field_stats', models.JSONField(default=dict)),
                ('average_processing_time', models.FloatField(default=0.0)),
                ('min_processing_time', models.FloatField(default=0.0)),
                ('max_processing_time', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'إحصائية الاستخراج',
                'verbose_name_plural': 'إحصائيات الاستخراج',
                'ordering': ['-date'],
            },
        ),
    ]
