# Generated by ChatGPT on 2026-01-22
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_extractionstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
                'verbose_name': 'فئة اقتراح',
                'verbose_name_plural': 'فئات الاقتراحات',
            },
        ),
        migrations.CreateModel(
            name='SuggestionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.suggestioncategory')),
            ],
            options={
                'ordering': ['order', 'value'],
                'verbose_name': 'عنصر اقتراح',
                'verbose_name_plural': 'عناصر الاقتراح',
                'unique_together': {('category', 'value')},
            },
        ),
    ]
