# Generated by ChatGPT on 2026-01-22
from django.db import migrations


def seed_suggestions(apps, schema_editor):
    Category = apps.get_model('core', 'SuggestionCategory')
    Item = apps.get_model('core', 'SuggestionItem')

    seed_data = {
        'issuing_entity': {
            'name': 'جهات الإصدار',
            'description': 'الوزارات والجهات المصدرة',
            'items': [
                'وزارة الداخلية',
                'وزارة العدل',
                'وزارة التربية',
                'وزارة الصحة',
                'وزارة الخارجية',
                'وزارة المالية',
            ],
        },
        'receiving_entity': {
            'name': 'جهات الاستقبال',
            'description': 'الأقسام المستلمة',
            'items': [
                'قسم المتابعة',
                'قسم الأرشيف',
                'قسم الإدارة',
                'قسم التدقيق',
                'قسم المستندات',
                'قسم المشاريع',
            ],
        },
        'secret_level': {
            'name': 'مستوى السرية',
            'description': 'تصنيف السرية',
            'items': ['اعتيادي', 'سري', 'سري للغاية'],
        },
        'book_kind': {
            'name': 'نوع الكتاب',
            'description': 'وارد/صادر',
            'items': ['incoming', 'outgoing'],
        },
    }

    for key, data in seed_data.items():
        category, _ = Category.objects.get_or_create(
            key=key,
            defaults={
                'name': data['name'],
                'description': data['description'],
                'is_active': True,
            }
        )
        for order, value in enumerate(data['items']):
            Item.objects.get_or_create(
                category=category,
                value=value,
                defaults={
                    'order': order,
                    'is_active': True,
                }
            )


def unseed_suggestions(apps, schema_editor):
    Category = apps.get_model('core', 'SuggestionCategory')
    Item = apps.get_model('core', 'SuggestionItem')
    keys = ['issuing_entity', 'receiving_entity', 'secret_level', 'book_kind']
    Item.objects.filter(category__key__in=keys).delete()
    Category.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_suggestion_models'),
    ]

    operations = [
        migrations.RunPython(seed_suggestions, reverse_code=unseed_suggestions),
    ]
