# Generated by Django 4.2.14 on 2026-04-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_postgresql_fts_extensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_number',
        ),
        migrations.RemoveField(
            model_name='book',
            name='issuing_entity',
        ),
        migrations.RemoveField(
            model_name='book',
            name='outgoing_incoming_number',
        ),
        migrations.RemoveField(
            model_name='book',
            name='receiving_entity',
        ),
    ]
