# Generated by Django 4.2.14 on 2026-04-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_extraction_kind_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('outgoing_internal', 'صادر داخلي'), ('outgoing_external', 'صادر خارجي'), ('incoming_internal', 'وارد داخلي'), ('incoming_external', 'وارد خارجي')], max_length=20, unique=True, verbose_name='نوع الكتاب')),
                ('prefix', models.CharField(blank=True, default='', help_text='بادئة اختيارية تُضاف قبل الرقم (مثال: و/, ص/)', max_length=20, verbose_name='البادئة')),
                ('next_number', models.PositiveIntegerField(default=1, help_text='الرقم التسلسلي التالي الذي سيُستخدم', verbose_name='الرقم التالي')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عدّاد تسلسلي',
                'verbose_name_plural': 'العدّادات التسلسلية',
            },
        ),
    ]
