# Generated by Django 4.2.14 on 2026-04-21 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_booksequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNumberReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('outgoing_internal', 'صادر داخلي'), ('outgoing_external', 'صادر خارجي'), ('incoming_internal', 'وارد داخلي'), ('incoming_external', 'وارد خارجي')], max_length=20, verbose_name='نوع الكتاب')),
                ('number', models.PositiveIntegerField(verbose_name='رقم القيد')),
                ('prefix', models.CharField(blank=True, default='', max_length=20, verbose_name='البادئة')),
                ('year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('formatted', models.CharField(max_length=60, verbose_name='الرقم المنسق')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('used', 'مُستخدم'), ('voided', 'ملغي'), ('expired', 'منتهي الصلاحية'), ('reactivated', 'مُعاد تفعيله')], db_index=True, default='active', max_length=15, verbose_name='الحالة')),
                ('void_reason', models.CharField(blank=True, choices=[('user_cancelled', 'ألغاه المستخدم'), ('timeout', 'انتهت المهلة'), ('year_reset', 'إعادة تعيين سنوية'), ('reactivated', 'أُعيد تفعيله')], default='', max_length=20, verbose_name='سبب الإلغاء')),
                ('note', models.TextField(blank=True, default='', verbose_name='ملاحظة')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحجز')),
                ('expires_at', models.DateTimeField(verbose_name='ينتهي في')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستخدام')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإلغاء')),
                ('book', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='number_reservation', to='core.book', verbose_name='الكتاب المرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حجز رقم قيد',
                'verbose_name_plural': 'حجوزات أرقام القيود',
                'ordering': ['-reserved_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='core_booknu_user_id_fef832_idx'), models.Index(fields=['kind', 'year', 'number'], name='core_booknu_kind_0437ac_idx')],
            },
        ),
    ]
