# Generated by Django 4.2.14 on 2026-04-21 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_book_number_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='', max_length=200, verbose_name='اسم المؤسسة')),
                ('org_email', models.EmailField(blank=True, default='', help_text='يُستخدم كـ From address في جميع الإيميلات', max_length=254, verbose_name='بريد المؤسسة الرسمي')),
                ('reply_to', models.EmailField(blank=True, default='', help_text='إذا تُرك فارغاً يُستخدم org_email', max_length=254, verbose_name='الرد على')),
                ('email_signature', models.TextField(blank=True, default='', help_text='يُضاف في نهاية كل إيميل (HTML مدعوم)', verbose_name='التوقيع')),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=200, verbose_name='خادم SMTP')),
                ('smtp_port', models.PositiveSmallIntegerField(default=587, verbose_name='المنفذ')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='TLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='SSL')),
                ('smtp_user', models.CharField(blank=True, default='', max_length=200, verbose_name='المستخدم')),
                ('smtp_password', models.CharField(blank=True, default='', help_text='تُخزَّن مشفرة', max_length=200, verbose_name='كلمة المرور')),
                ('is_active', models.BooleanField(default=False, verbose_name='تفعيل إرسال الإيميل')),
                ('send_on_save', models.BooleanField(default=False, verbose_name='إرسال تلقائي عند حفظ كتاب')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات البريد',
                'verbose_name_plural': 'إعدادات البريد',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='العنوان البريدي'),
        ),
        migrations.AddField(
            model_name='entity',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='مسؤول الاتصال'),
        ),
        migrations.AddField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='بريد الجهة للمراسلات الرسمية (اختياري)', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='entity',
            name='email_cc',
            field=models.CharField(blank=True, default='', help_text='عناوين بريد إضافية مفصولة بفاصلة (اختيارية)', max_length=500, verbose_name='نسخة إلى (CC)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='entity',
            name='notify_on_receive',
            field=models.BooleanField(default=False, help_text='يُرسَل بريد تلقائي للجهة عند تسجيل كتاب وارد منها', verbose_name='إشعار عند استلام كتاب منها'),
        ),
        migrations.AddField(
            model_name='entity',
            name='notify_on_send',
            field=models.BooleanField(default=False, help_text='يُرسَل بريد تلقائي للجهة عند تسجيل كتاب صادر إليها', verbose_name='إشعار عند إرسال كتاب إليها'),
        ),
        migrations.AddField(
            model_name='entity',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف'),
        ),
        migrations.CreateModel(
            name='BookEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(max_length=255, verbose_name='إلى')),
                ('cc_addresses', models.CharField(blank=True, default='', max_length=500, verbose_name='CC')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='النص')),
                ('trigger', models.CharField(choices=[('auto', 'تلقائي عند الحفظ'), ('manual', 'يدوي'), ('reminder', 'تذكير متابعة')], default='auto', max_length=10)),
                ('status', models.CharField(choices=[('sent', 'أُرسِل'), ('failed', 'فشل'), ('pending', 'في الانتظار')], db_index=True, default='pending', max_length=10)),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='رسالة الخطأ')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='أُرسِل في')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تأكيد التسليم')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.book', verbose_name='الكتاب')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='core.entity', verbose_name='الجهة')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أرسله')),
            ],
            options={
                'verbose_name': 'سجل إيميل',
                'verbose_name_plural': 'سجلات الإيميل',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['book', 'status'], name='core_bookem_book_id_0f066f_idx'), models.Index(fields=['sent_at'], name='core_bookem_sent_at_5cf0fe_idx')],
            },
        ),
    ]
