# Generated by Django 4.2.14 on 2026-04-21 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_entity_email_and_email_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='الموضوع')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('waiting', 'بانتظار رد'), ('replied', 'تم الرد'), ('closed', 'مغلق')], db_index=True, default='open', max_length=10)),
                ('ref_message_id', models.CharField(blank=True, default='', help_text='Message-ID للإيميل الأول — يُستخدم لربط الردود الواردة', max_length=500, verbose_name='Message-ID الأصلي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_threads', to='core.book', verbose_name='الكتاب المرتبط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_threads', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_threads', to='core.entity', verbose_name='الجهة')),
            ],
            options={
                'verbose_name': 'خيط مراسلة',
                'verbose_name_plural': 'خيوط المراسلات',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddField(
            model_name='bookemaillog',
            name='smtp_message_id',
            field=models.CharField(blank=True, default='', help_text='يُستخدم لربط الردود الواردة بهذا الإيميل', max_length=500, verbose_name='SMTP Message-ID'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='imap_folder',
            field=models.CharField(blank=True, default='INBOX', max_length=100, verbose_name='المجلد'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='imap_host',
            field=models.CharField(blank=True, default='', help_text='مثال: imap.gmail.com', max_length=200, verbose_name='خادم IMAP'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='imap_last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='imap_password',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='كلمة مرور IMAP'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='imap_port',
            field=models.PositiveSmallIntegerField(default=993, verbose_name='منفذ IMAP'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='imap_sync_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل استقبال الردود تلقائياً'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='imap_use_ssl',
            field=models.BooleanField(default=True, verbose_name='SSL للـ IMAP'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='imap_user',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='مستخدم IMAP'),
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('slug', models.SlugField(help_text='معرّف فريد للاستخدام البرمجي', max_length=100, unique=True)),
                ('applicable_kind', models.CharField(choices=[('any', 'كل الأنواع'), ('incoming', 'وارد فقط'), ('outgoing', 'صادر فقط')], default='any', max_length=10, verbose_name='يُطبَّق على')),
                ('subject_template', models.CharField(help_text='يدعم: {{book.our_number}}, {{book.title}}, {{entity.name}}', max_length=300, verbose_name='موضوع الإيميل')),
                ('body_html', models.TextField(help_text='يدعم: {{book.our_number}}, {{book.title}}, {{entity.name}}, {{user.get_full_name}}', verbose_name='نص الإيميل (HTML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي لهذا النوع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'قالب إيميل',
                'verbose_name_plural': 'قوالب الإيميلات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bookemaillog',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='core.emailthread', verbose_name='الخيط'),
        ),
        migrations.CreateModel(
            name='IncomingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=255, verbose_name='من')),
                ('from_name', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم المرسل')),
                ('reply_to', models.CharField(blank=True, default='', max_length=255, verbose_name='الرد على')),
                ('subject', models.CharField(blank=True, default='', max_length=300, verbose_name='الموضوع')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='النص HTML')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='النص العادي')),
                ('message_id', models.CharField(help_text='لمنع التكرار عند المزامنة', max_length=500, unique=True, verbose_name='Message-ID')),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=500, verbose_name='In-Reply-To')),
                ('imap_uid', models.PositiveIntegerField(blank=True, null=True, verbose_name='IMAP UID')),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='استُلِم في')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت المزامنة')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='مقروء')),
                ('is_spam', models.BooleanField(default=False, verbose_name='بريد مزعج')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_emails', to='core.emailthread', verbose_name='الخيط')),
            ],
            options={
                'verbose_name': 'إيميل وارد',
                'verbose_name_plural': 'الإيميلات الواردة',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['thread', 'is_read'], name='core_incomi_thread__820a35_idx'), models.Index(fields=['received_at'], name='core_incomi_receive_38d2eb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['status', '-last_activity'], name='core_emailt_status_7b67a0_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['book'], name='core_emailt_book_id_279b67_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['entity'], name='core_emailt_entity__66b419_idx'),
        ),
    ]
