# Generated by Django 4.2.14 on 2026-04-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_mail_system_phase1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataextractionresult',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المعالجة'), ('extracted', 'مستخرج'), ('reviewed', 'تم المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_deleted'], name='book_is_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['kind'], name='book_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_deleted', 'created_by', 'final_status'], name='book_user_status_idx'),
        ),
    ]
