# Generated by Django 4.2.14 on 2026-04-27 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_phase2_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataextractionresult',
            name='attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_extraction', to='core.attachment'),
        ),
        migrations.AlterField(
            model_name='dataextractionresult',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='core.book'),
        ),
        migrations.AlterField(
            model_name='dataextractionresult',
            name='ocr_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction', to='core.ocrresult'),
        ),
        migrations.AlterField(
            model_name='mergelog',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_logs', to='core.attachment'),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_result', to='core.attachment'),
        ),
    ]
