# Generated by Django 4.2.14 on 2026-04-27 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_p01_entity_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='الاسم')),
                ('slug', models.SlugField(help_text='يُستخدم في URLs (يُولَّد تلقائياً من name لو ترك فارغاً)', max_length=60, unique=True, verbose_name='المعرّف')),
                ('color', models.CharField(blank=True, default='', help_text='رمز hex مثل #ff5722 (اختياري للعرض)', max_length=7, verbose_name='اللون')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'وَسم',
                'verbose_name_plural': 'الوُسوم',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bookhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.RemoveIndex(
            model_name='bookhistory',
            name='core_bookhi_action_beaf6f_idx',
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='author_snapshot',
            field=models.CharField(blank=True, default='', help_text='يُحفظ عند الإنشاء ويبقى حتى لو حُذف المستخدم', max_length=150, verbose_name='اسم الكاتب (snapshot)'),
        ),
        migrations.AddField(
            model_name='bookhistory',
            name='by_snapshot',
            field=models.CharField(blank=True, default='', help_text='يُحفظ عند الإنشاء لضمان بقاء سجل التدقيق حتى بعد حذف المستخدم', max_length=150, verbose_name='اسم المنفّذ (snapshot)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('book', 'كتاب'), ('attachment', 'مرفق'), ('extraction', 'استخراج بيانات'), ('merge', 'دمج ملفات'), ('email', 'بريد إلكتروني'), ('system', 'نظام')], default='system', max_length=20, verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, default='', help_text='URL للإحالة عند النقر على الإشعار', max_length=500, verbose_name='الرابط'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('urgent', 'عاجل')], default='info', max_length=10, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='username_snapshot',
            field=models.CharField(blank=True, default='', help_text='يُحفظ عند الإنشاء لضمان بقاء سجل التدقيق حتى لو حُذف المستخدم', max_length=150, verbose_name='اسم المستخدم (snapshot)'),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_comments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='bookhistory',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('edit', 'تعديل'), ('update_notes', 'تحديث ملاحظات'), ('status', 'تغيير الحالة'), ('delete', 'حذف (soft)'), ('restore', 'استعادة'), ('overdue', 'تجاوز الاستحقاق'), ('attach', 'إرفاق ملف'), ('attach-fail', 'فشل إرفاق'), ('delete-attachment', 'حذف مرفق'), ('replace-attachment', 'استبدال مرفق'), ('restore-attachment', 'استعادة مرفق'), ('merge', 'دمج ملفات'), ('merge-pages', 'دمج صفحات'), ('remove-pages', 'إزالة صفحات')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookhistory',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='core.attachment'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='bookcomment',
            index=models.Index(fields=['book', '-created_at'], name='core_bookco_book_id_be3ace_idx'),
        ),
        migrations.AddIndex(
            model_name='bookhistory',
            index=models.Index(fields=['action', '-created_at'], name='core_bookhi_action_e96b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notif_user_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category', '-created_at'], name='notif_category_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', '-created_at'], name='notif_priority_idx'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='core.tag', verbose_name='الوُسوم'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active', 'name'], name='core_tag_is_acti_c4eddd_idx'),
        ),
    ]
