# Generated by Django 4.2.14 on 2026-04-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_book_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='archived_issuing_names',
            field=models.JSONField(blank=True, default=list, verbose_name='أسماء جهات مُصدِرة محذوفة (أرشيف)'),
        ),
        migrations.AddField(
            model_name='book',
            name='archived_receiving_names',
            field=models.JSONField(blank=True, default=list, verbose_name='أسماء جهات مُستلمة محذوفة (أرشيف)'),
        ),
    ]
