# Generated by Django 4.2.14 on 2026-06-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_networksettings_password_enc_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksequence',
            name='next_number',
            field=models.PositiveIntegerField(default=1, verbose_name='الرقم التالي'),
        ),
    ]
