# Generated by Django 4.2.14 on 2026-06-28 06:14

from django.db import migrations, models


def _normalize_document_types(apps, schema_editor):
    """تطبيع document_type القديم (طيّ المسافات) ليتّسق مع تطبيع BookForm الجديد،
    فيصير فلتر الأضابير (مطابقة دقيقة) صحيحاً على كل البيانات. يحدّث المختلف فقط."""
    Book = apps.get_model('core', 'Book')
    updates = []
    for pk, dt in Book.objects.exclude(document_type='').values_list('id', 'document_type'):
        norm = ' '.join((dt or '').split())
        if norm != dt:
            updates.append(Book(id=pk, document_type=norm))
    if updates:
        Book.objects.bulk_update(updates, ['document_type'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_booksequence_next_number'),
    ]

    operations = [
        migrations.RunPython(_normalize_document_types, migrations.RunPython.noop),
        migrations.AddField(
            model_name='emailsettings',
            name='org_section',
            field=models.CharField(blank=True, default='', help_text='يظهر في ترويسة التقارير المطبوعة', max_length=200, verbose_name='اسم القسم'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='org_unit',
            field=models.CharField(blank=True, default='', help_text='يظهر في ترويسة التقارير المطبوعة', max_length=200, verbose_name='اسم الوحدة'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='org_name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم الشركة/المؤسسة'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-date', '-id'], name='book_date_idx'),
        ),
    ]
