# Generated by Django 4.2.14 on 2026-06-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_dossier_org_identity_and_date_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScanSettings',
        ),
    ]
