# Generated by Django 4.2.14 on 2026-06-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_old_scan_settings'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('our_number', ''), _negated=True), fields=('our_number', 'kind'), name='uniq_book_our_number_kind'),
        ),
    ]
