# Generated by Django 4.2.14 on 2026-07-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_book_uniq_book_our_number_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterheadMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterhead', models.TextField(help_text='نصّ أعلى المستند (الترويسة) — مصدر التشابه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.book')),
                ('issuing_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letterhead_as_issuer', to='core.entity', verbose_name='الجهة المُصدِرة المؤكَّدة')),
                ('receiving_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letterhead_as_receiver', to='core.entity', verbose_name='الجهة المستقبِلة المؤكَّدة')),
            ],
            options={
                'verbose_name': 'ذاكرة ترويسة',
                'verbose_name_plural': 'ذاكرة الترويسات',
                'ordering': ['-created_at'],
            },
        ),
    ]
