# Generated by Django 4.2.14 on 2026-07-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_normalize_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('app_name', models.CharField(default='نظام الكتب', max_length=100, verbose_name='اسم النظام')),
                ('brand_subtitle', models.CharField(blank=True, default='أرشفة موحدة ومتابعة تشغيلية ضمن واجهة ديسكتوب ثابتة', max_length=200, verbose_name='سطر الوصف في الترويسة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
