# Generated by Django 4.2.14 on 2026-07-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('overdue_enabled', models.BooleanField(default=True, verbose_name='تفعيل إشعارات التأخّر')),
                ('notify_admins', models.BooleanField(default=True, verbose_name='إشعار المدراء داخل النظام')),
                ('notify_creator', models.BooleanField(default=True, verbose_name='إشعار مُنشئ الكتاب')),
                ('email_admins', models.BooleanField(default=False, help_text='يتطلّب تفعيل إعدادات البريد', verbose_name='إرسال بريد ملخّص للمدراء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الإشعارات',
                'verbose_name_plural': 'إعدادات الإشعارات',
            },
        ),
    ]
