# Generated by Django 4.2.14 on 2026-07-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_notificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False, verbose_name='تفعيل النسخ التلقائي')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], default='daily', max_length=10, verbose_name='التكرار')),
                ('hour', models.PositiveSmallIntegerField(default=2, verbose_name='ساعة التشغيل (0-23)')),
                ('retention_days', models.PositiveSmallIntegerField(default=30, verbose_name='مدة الاحتفاظ (يوم)')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل ناجح')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات النسخ الاحتياطي',
                'verbose_name_plural': 'إعدادات النسخ الاحتياطي',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('password_min_length', models.PositiveSmallIntegerField(default=8, verbose_name='الحد الأدنى لطول كلمة المرور')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الأمان',
                'verbose_name_plural': 'إعدادات الأمان',
            },
        ),
    ]
