# Generated by Django 4.2.14 on 2026-07-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_perpetual_numbering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksequence',
            name='year',
            field=models.PositiveSmallIntegerField(default=2026, help_text='سنة إنشاء/بذر العدّاد — للسجل فقط؛ لم يعد يُستخدم للتصفير (الترقيم دائم)', verbose_name='سنة بدء العدّاد'),
        ),
    ]
