# Generated by Django 4.2.14 on 2026-07-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_search_trgm_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknumberreservation',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='نهاية فترة السماح'),
        ),
        migrations.AddField(
            model_name='booknumberreservation',
            name='is_recycled',
            field=models.BooleanField(default=False, verbose_name='رقم مُدوّر'),
        ),
        migrations.AddField(
            model_name='booknumberreservation',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر نبضة حضور'),
        ),
        migrations.AlterField(
            model_name='booknumberreservation',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('used', 'مُستخدم'), ('voided', 'ملغي'), ('expired', 'منتهي الصلاحية'), ('reactivated', 'مُعاد تفعيله'), ('cooldown', 'فترة سماح')], db_index=True, default='active', max_length=15, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='booknumberreservation',
            name='void_reason',
            field=models.CharField(blank=True, choices=[('user_cancelled', 'ألغاه المستخدم'), ('timeout', 'انتهت المهلة'), ('year_reset', 'إعادة تعيين سنوية'), ('reactivated', 'أُعيد تفعيله'), ('forced_disconnect', 'انقطاع قسريّ'), ('recycled', 'أُعيد تدويره')], default='', max_length=20, verbose_name='سبب الإلغاء'),
        ),
    ]
