# Generated by Django 4.2.14 on 2026-07-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_booknumberreservation_cooldown_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookemaillog',
            name='smtp_message_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='يُستخدم لربط الردود الواردة بهذا الإيميل', max_length=500, verbose_name='SMTP Message-ID'),
        ),
    ]
