# Generated by Django 4.2.14 on 2026-08-10 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0056_bookemaillog_message_id_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'في الانتظار'), ('running', 'قيد التنفيذ'), ('done', 'انتهت'), ('failed', 'فشلت'), ('cancelled', 'أُلغيت')], db_index=True, default='queued', max_length=12, verbose_name='الحالة')),
                ('phase', models.CharField(blank=True, default='', max_length=200, verbose_name='المرحلة')),
                ('done_count', models.PositiveIntegerField(default=0, verbose_name='المُنجَز')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='الإجمالي')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='المعاملات (بلا اعتماد)')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='الخلاصة')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='الخطأ')),
                ('cancel_requested', models.BooleanField(default=False, verbose_name='طُلب الإلغاء')),
                ('pid', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرّف العملية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهت في')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مهمّة دمج',
                'verbose_name_plural': 'مهامّ الدمج',
                'ordering': ['-created_at'],
            },
        ),
    ]
