# Generated by Django 4.2.14 on 2026-08-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_restorejob'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='uniq_book_our_number_kind',
        ),
        migrations.AddField(
            model_name='book',
            name='is_training',
            field=models.BooleanField(db_index=True, default=False, help_text='أُدخل أثناء فترة التدريب. رقمه من فضاء منفصل (T…) فلا يستهلك السلسلة الرسمية، ويُحذف كلّه عند التدشين لأن أصله موجود في النظام القديم.', verbose_name='كتاب تدريب'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('our_number', ''), _negated=True), ('source_ref', ''), models.Q(('kind', 'outgoing_external'), _negated=True), ('is_deleted', False)), fields=('our_number', 'kind'), name='uniq_book_our_number_kind'),
        ),
    ]
