# Generated by Django 4.2.14 on 2026-08-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_numbering_training_and_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'حمولة مسح',
                'verbose_name_plural': 'حمولات المسح',
                'indexes': [models.Index(fields=['-created_at'], name='core_scanpa_created_728806_idx')],
            },
        ),
    ]
