# Generated by Django 4.2.14 on 2026-08-26 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_swap_imported_incoming_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookemaillog',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.book', verbose_name='الكتاب'),
        ),
    ]
