# Generated by Django 4.2.14 on 2026-08-27 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_bookemaillog_optional_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookemaillog',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر محاولة'),
        ),
        migrations.AddField(
            model_name='bookemaillog',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد المحاولات'),
        ),
        migrations.AddField(
            model_name='bookemaillog',
            name='retry_of',
            field=models.ForeignKey(blank=True, help_text='غير فارغ ⟵ هذا الصفّ محاولةُ إعادةٍ لا أصلاً: لا يدخل الطابور.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='core.bookemaillog', verbose_name='محاولةٌ لـ'),
        ),
        migrations.AlterField(
            model_name='bookemaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'أُرسِل'), ('failed', 'فشل'), ('pending', 'في الانتظار'), ('abandoned', 'مُتروك بعد محاولات')], db_index=True, default='pending', max_length=10),
        ),
    ]
