# Generated by Django 4.2.14 on 2026-08-27 06:11

from django.db import migrations, models

DEFAULT_CODE = 'ش13'
DEFAULT_NAME = 'قسم المتابعة'


def assign_default_department(apps, schema_editor):
    """يُسنِد كلّ ما هو قائمٌ إلى القسم الافتراضيّ — شرطُ التوافق.

    قاعدةُ الخطّة: تنصيبُ قسم المتابعة يعمل بعد كلّ مرحلةٍ بلا خطوةٍ يدويّة.
    فالهجرة تُنشئ القسم إن غاب، وتُسنِد إليه **كلّ** الكتب — بما فيها المحذوفةُ
    ناعماً: المديرُ التاريخيّ في الهجرات غير مُرشَّح، وهذا هو الصواب هنا (كتابٌ
    محذوفٌ بلا قسمٍ يصير غيرَ قابلٍ للاستعادة إلى مكانه).

    وتُنشئ ملفّاً لكلّ مستخدمٍ قائم: بدونه يسقط الموظّف إلى «كتبي أنا» بدل
    «كتب قسمي» — تضييقُ رؤيةٍ صامت. حسابان مقيسان يعتمدان على هذا (2,067 و61
    كتاباً) لأنّهما كانا يريان الكلّ بصفة ``is_staff``.
    """
    Department = apps.get_model('core', 'Department')
    Book = apps.get_model('core', 'Book')
    UserProfile = apps.get_model('core', 'UserProfile')
    User = apps.get_model('auth', 'User')

    dept = Department.objects.filter(code=DEFAULT_CODE).first()
    if dept is None:
        dept = Department.objects.create(name=DEFAULT_NAME, code=DEFAULT_CODE)

    Book.objects.filter(department__isnull=True).update(department=dept)

    existing = set(UserProfile.objects.values_list('user_id', flat=True))
    UserProfile.objects.bulk_create([
        UserProfile(user_id=uid, department=dept)
        for uid in User.objects.exclude(id__in=existing).values_list('id', flat=True)
    ])


def unassign(apps, schema_editor):
    """تراجعٌ آمن: يفكّ الربط ولا يحذف الأقسام ولا الملفّات (قد تكون أُنشئت يدويّاً)."""
    apps.get_model('core', 'Book').objects.update(department=None)

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_department_and_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='core.department', verbose_name='القسم'),
        ),
            migrations.RunPython(assign_default_department, unassign),
    ]
