# Generated by Django 4.2.14 on 2026-08-27 06:20

from django.db import migrations, models

def attach_sequences_to_default(apps, schema_editor):
    """العدّادات القائمة تصير عدّادات القسم الافتراضيّ.

    قِيست الأربعة الحيّة قبل الهجرة (وارد داخليّ 3914 · صادر داخليّ 715 ·
    وارد خارجيّ 605 · صادر خارجيّ 1) — وهي دفتر قسم المتابعة، فتُنسب إليه
    بدل أن تبقى بلا قسمٍ فتصطدم بقيد التفرّد الجديد.
    """
    Department = apps.get_model('core', 'Department')
    BookSequence = apps.get_model('core', 'BookSequence')

    dept = Department.objects.filter(code='ش13').first() or Department.objects.order_by('id').first()
    if dept is None:
        return   # تنصيبٌ جديدٌ بلا أقسام: لا عدّادات أصلاً
    BookSequence.objects.filter(department__isnull=True).update(department=dept)


def detach_sequences(apps, schema_editor):
    apps.get_model('core', 'BookSequence').objects.update(department=None)

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_book_department'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='uniq_book_our_number_kind',
        ),
        migrations.AddField(
            model_name='booksequence',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='core.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='booksequence',
            name='kind',
            field=models.CharField(choices=[('outgoing_internal', 'صادر داخلي'), ('outgoing_external', 'صادر خارجي'), ('incoming_internal', 'وارد داخلي'), ('incoming_external', 'وارد خارجي')], max_length=20, verbose_name='نوع الكتاب'),
        ),
        migrations.RunPython(attach_sequences_to_default, detach_sequences),
        migrations.AlterUniqueTogether(
            name='booksequence',
            unique_together={('department', 'kind')},
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('our_number', ''), _negated=True), ('source_ref', ''), models.Q(('kind', 'outgoing_external'), _negated=True), ('is_deleted', False)), fields=('department', 'our_number', 'kind'), name='uniq_book_number_kind_dept'),
        ),
    ]
