# Generated by Django 4.2.14 on 2026-08-30 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0065_sequence_per_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='سُحب في')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='السبب')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_grants', to='core.book')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_grants_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تفويض اطّلاع',
                'verbose_name_plural': 'تفويضات الاطّلاع',
                'indexes': [models.Index(fields=['user'], name='secret_grant_user_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='secretaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('book', 'user'), name='uniq_live_secret_grant'),
        ),
    ]
