# Generated by Django 4.2.14 on 2026-08-30 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0066_secret_access_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhistory',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('edit', 'تعديل'), ('update_notes', 'تحديث ملاحظات'), ('status', 'تغيير الحالة'), ('delete', 'حذف (soft)'), ('restore', 'استعادة'), ('overdue', 'تجاوز الاستحقاق'), ('attach', 'إرفاق ملف'), ('attach-fail', 'فشل إرفاق'), ('delete-attachment', 'حذف مرفق'), ('replace-attachment', 'استبدال مرفق'), ('restore-attachment', 'استعادة مرفق'), ('merge', 'دمج ملفات'), ('merge-pages', 'دمج صفحات'), ('remove-pages', 'إزالة صفحات'), ('link-added', 'ربط بكتاب'), ('link-removed', 'فكّ ربط')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='BookLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('reply', 'جواب على'), ('followup', 'إلحاقاً بـ'), ('refers', 'إشارة إلى'), ('confirmation', 'تأكيد على')], max_length=16, verbose_name='العلاقة')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_links', to=settings.AUTH_USER_MODEL)),
                ('from_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='core.book', verbose_name='من كتاب')),
                ('to_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links_in', to='core.book', verbose_name='إلى كتاب')),
            ],
            options={
                'verbose_name': 'رابط بين كتابين',
                'verbose_name_plural': 'روابط الكتب',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_book', 'relation'], name='booklink_to_idx'), models.Index(fields=['from_book', 'relation'], name='booklink_from_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='booklink',
            constraint=models.UniqueConstraint(fields=('from_book', 'to_book', 'relation'), name='uniq_book_link'),
        ),
        migrations.AddConstraint(
            model_name='booklink',
            constraint=models.CheckConstraint(check=models.Q(('from_book', models.F('to_book')), _negated=True), name='book_link_not_self'),
        ),
    ]
