# Generated by Django 4.2.14 on 2026-08-30 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0067_book_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhistory',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('edit', 'تعديل'), ('update_notes', 'تحديث ملاحظات'), ('status', 'تغيير الحالة'), ('delete', 'حذف (soft)'), ('restore', 'استعادة'), ('overdue', 'تجاوز الاستحقاق'), ('attach', 'إرفاق ملف'), ('attach-fail', 'فشل إرفاق'), ('delete-attachment', 'حذف مرفق'), ('replace-attachment', 'استبدال مرفق'), ('restore-attachment', 'استعادة مرفق'), ('merge', 'دمج ملفات'), ('merge-pages', 'دمج صفحات'), ('remove-pages', 'إزالة صفحات'), ('link-added', 'ربط بكتاب'), ('link-removed', 'فكّ ربط'), ('referral', 'تفريق/إحالة'), ('referral-received', 'استلام الإحالة'), ('referral-done', 'إنجاز الإحالة'), ('referral-returned', 'إعادة الإحالة'), ('reminder', 'تنبيه')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='BookReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('action', 'للتنفيذ'), ('info', 'للعلم')], default='action', max_length=8, verbose_name='الغرض')),
                ('margin', models.TextField(blank=True, verbose_name='التوجيه/الهامش')),
                ('margin_crop', models.JSONField(blank=True, null=True, verbose_name='قصاصة الهامش')),
                ('status', models.CharField(choices=[('sent', 'مُرسَل'), ('received', 'مستلَم'), ('done', 'منجَز'), ('returned', 'مُعاد')], db_index=True, default='sent', max_length=10, verbose_name='الحالة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='موعد الإنجاز')),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تنبيه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_assigned', to=settings.AUTH_USER_MODEL, verbose_name='المكلَّف')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.book', verbose_name='الكتاب')),
                ('closed_by_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closes_referrals', to='core.booklink', verbose_name='أُقفل بالجواب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_created', to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_out', to='core.department', verbose_name='من قسم')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals_in', to='core.department', verbose_name='إلى قسم/وحدة')),
                ('to_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals_in', to='core.entity', verbose_name='إلى جهة خارجيّة')),
                ('via_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_via', to='core.book', verbose_name='المذكّرة الصادرة')),
            ],
            options={
                'verbose_name': 'إحالة',
                'verbose_name_plural': 'الإحالات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_department', 'status'], name='referral_dept_status_idx'), models.Index(fields=['status', 'purpose', 'due_date'], name='referral_queue_idx'), models.Index(fields=['book'], name='referral_book_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bookreferral',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('to_department__isnull', False), ('to_entity__isnull', True)), models.Q(('to_department__isnull', True), ('to_entity__isnull', False)), _connector='OR'), name='referral_exactly_one_target'),
        ),
    ]
