# Generated by Django 4.2.14 on 2026-08-30 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0068_book_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhistory',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('edit', 'تعديل'), ('update_notes', 'تحديث ملاحظات'), ('status', 'تغيير الحالة'), ('delete', 'حذف (soft)'), ('restore', 'استعادة'), ('overdue', 'تجاوز الاستحقاق'), ('attach', 'إرفاق ملف'), ('attach-fail', 'فشل إرفاق'), ('delete-attachment', 'حذف مرفق'), ('replace-attachment', 'استبدال مرفق'), ('restore-attachment', 'استعادة مرفق'), ('merge', 'دمج ملفات'), ('merge-pages', 'دمج صفحات'), ('remove-pages', 'إزالة صفحات'), ('link-added', 'ربط بكتاب'), ('link-removed', 'فكّ ربط'), ('referral', 'تفريق/إحالة'), ('referral-received', 'استلام الإحالة'), ('referral-done', 'إنجاز الإحالة'), ('referral-returned', 'إعادة الإحالة'), ('reminder', 'تنبيه'), ('custody', 'انتقال عهدة')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('intake', 'قيدٌ في السجلّ'), ('unit_receipt', 'استلامُ وحدة'), ('archive_done', 'تمامُ أرشفة'), ('courier_pickup', 'تسليمٌ لمتعهّد البريد'), ('return', 'إعادة')], db_index=True, max_length=20, verbose_name='الحدث')),
                ('to_holder_name', models.CharField(blank=True, max_length=120, verbose_name='بعهدة (اسم)')),
                ('signed_at', models.DateTimeField(db_index=True, verbose_name='وقت التوقيع')),
                ('signature_mode', models.CharField(choices=[('paper', 'توقيعٌ ورقيّ'), ('digital', 'إقرارٌ في النظام')], default='paper', max_length=10, verbose_name='نوعُ التوقيع')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='core.book', verbose_name='الكتاب')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_recorded', to=settings.AUTH_USER_MODEL, verbose_name='سجّله')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to='core.bookreferral', verbose_name='الإحالة')),
                ('to_holder_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_held', to='core.department', verbose_name='بعهدة قسم/وحدة')),
                ('to_holder_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_held', to=settings.AUTH_USER_MODEL, verbose_name='بعهدة موظّف')),
            ],
            options={
                'verbose_name': 'حدث عهدة',
                'verbose_name_plural': 'سجلّ العهدة',
                'ordering': ['-signed_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='current_custody',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.custodyevent', verbose_name='بعهدة'),
        ),
        migrations.AddIndex(
            model_name='custodyevent',
            index=models.Index(fields=['book', '-signed_at'], name='custody_book_idx'),
        ),
        migrations.AddIndex(
            model_name='custodyevent',
            index=models.Index(fields=['event', 'signed_at'], name='custody_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='custodyevent',
            constraint=models.CheckConstraint(check=models.Q(('to_holder_department__isnull', False), ('to_holder_user__isnull', False), models.Q(('to_holder_name', ''), _negated=True), _connector='OR'), name='custody_has_a_holder'),
        ),
    ]
