# Generated by Django 4.2.14 on 2026-08-30 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0069_custody_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhistory',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('edit', 'تعديل'), ('update_notes', 'تحديث ملاحظات'), ('status', 'تغيير الحالة'), ('delete', 'حذف (soft)'), ('restore', 'استعادة'), ('overdue', 'تجاوز الاستحقاق'), ('attach', 'إرفاق ملف'), ('attach-fail', 'فشل إرفاق'), ('delete-attachment', 'حذف مرفق'), ('replace-attachment', 'استبدال مرفق'), ('restore-attachment', 'استعادة مرفق'), ('merge', 'دمج ملفات'), ('merge-pages', 'دمج صفحات'), ('remove-pages', 'إزالة صفحات'), ('link-added', 'ربط بكتاب'), ('link-removed', 'فكّ ربط'), ('referral', 'تفريق/إحالة'), ('referral-received', 'استلام الإحالة'), ('referral-done', 'إنجاز الإحالة'), ('referral-returned', 'إعادة الإحالة'), ('reminder', 'تنبيه'), ('custody', 'انتقال عهدة'), ('registered', 'قُيّد في دفتر قسم')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='BookRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming_internal', 'وارد داخلي'), ('incoming_external', 'وارد خارجي')], default='incoming_internal', max_length=20, verbose_name='النوع')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='رقم الوارد')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ القيد')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.book', verbose_name='الكتاب')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='core.department', verbose_name='القسم')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_made', to=settings.AUTH_USER_MODEL)),
                ('via_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='core.bookreferral', verbose_name='عن إحالة')),
            ],
            options={
                'verbose_name': 'قيد في دفتر',
                'verbose_name_plural': 'القيود',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['department', 'direction'], name='registration_dept_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bookregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('department', 'direction', 'number'), name='uniq_registration_per_department'),
        ),
        migrations.AddConstraint(
            model_name='bookregistration',
            constraint=models.UniqueConstraint(fields=('book', 'department'), name='uniq_registration_book_department'),
        ),
    ]
