# Generated by Django 4.2.14 on 2026-08-30 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_book_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhistory',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('edit', 'تعديل'), ('update_notes', 'تحديث ملاحظات'), ('status', 'تغيير الحالة'), ('delete', 'حذف (soft)'), ('restore', 'استعادة'), ('overdue', 'تجاوز الاستحقاق'), ('attach', 'إرفاق ملف'), ('attach-fail', 'فشل إرفاق'), ('delete-attachment', 'حذف مرفق'), ('replace-attachment', 'استبدال مرفق'), ('restore-attachment', 'استعادة مرفق'), ('merge', 'دمج ملفات'), ('merge-pages', 'دمج صفحات'), ('remove-pages', 'إزالة صفحات'), ('link-added', 'ربط بكتاب'), ('link-removed', 'فكّ ربط'), ('referral', 'تفريق/إحالة'), ('referral-received', 'استلام الإحالة'), ('referral-done', 'إنجاز الإحالة'), ('referral-returned', 'إعادة الإحالة'), ('reminder', 'تنبيه'), ('custody', 'انتقال عهدة'), ('registered', 'قُيّد في دفتر قسم'), ('circular', 'تعميم على عنقود')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='EntityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم العنقود')),
                ('auto_rule', models.CharField(blank=True, choices=[('all_registry_departments', 'كلُّ الأقسام المسجّلة النشطة')], max_length=32, verbose_name='قاعدة ديناميكيّة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='core.entity', verbose_name='الأعضاء')),
            ],
            options={
                'verbose_name': 'عنقود جهات',
                'verbose_name_plural': 'عناقيد الجهات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='sent_to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='core.entitygroup', verbose_name='عُمِّم على'),
        ),
    ]
