# Generated by Django 4.2.14 on 2026-08-30 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_entity_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='book',
            field=models.ForeignKey(blank=True, help_text='بدونه يستحيل سؤال «مَن قرأ هذا الكتاب؟»', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='core.book', verbose_name='الكتاب'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد المرّات'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='day',
            field=models.DateField(blank=True, null=True, verbose_name='اليوم'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='core.department', verbose_name='قسم الفاعل'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مرّة'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('VIEW_BOOK', 'فتح كتاب'), ('VIEW_ATTACHMENT', 'عرض مرفق'), ('DOWNLOAD_ATTACHMENT', 'تحميل مرفق'), ('EXPORT_DATA', 'تصدير بيانات'), ('PRINT', 'طباعة'), ('SHARED_LINK_OPEN', 'فتح رابط مشاركة'), ('SECRET_VIEW', 'اطّلاع على سرّي'), ('VIEW_AUDIT_LOG', 'فتح سجلّ الحركات'), ('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('LOGIN_FAILED', 'محاولة دخول فاشلة'), ('CREATE_BOOK', 'إنشاء كتاب'), ('EDIT_BOOK', 'تعديل كتاب'), ('DELETE_BOOK', 'حذف كتاب'), ('BACKUP_DATA', 'نسخ احتياطي'), ('SCANNER', 'استخدام السكانر')], max_length=50, verbose_name='الإجراء'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['book', '-timestamp'], name='activity_book_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['department', '-timestamp'], name='activity_dept_idx'),
        ),
        migrations.AddConstraint(
            model_name='useractivitylog',
            constraint=models.UniqueConstraint(condition=models.Q(('action__in', ('VIEW_BOOK', 'VIEW_ATTACHMENT'))), fields=('user', 'book', 'action', 'day'), name='uniq_folded_activity_per_day'),
        ),
    ]
