# Generated by Django 4.2.14 on 2026-08-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('VIEW_BOOK', 'فتح كتاب'), ('VIEW_ATTACHMENT', 'عرض مرفق'), ('DOWNLOAD_ATTACHMENT', 'تحميل مرفق'), ('EXPORT_DATA', 'تصدير بيانات'), ('PRINT', 'طباعة'), ('SHARED_LINK_OPEN', 'فتح رابط مشاركة'), ('SECRET_VIEW', 'اطّلاع على سرّي'), ('VIEW_AUDIT_LOG', 'فتح سجلّ الحركات'), ('CREATE_DEPARTMENT', 'إنشاء قسم'), ('EDIT_DEPARTMENT', 'تعديل قسم'), ('ASSIGN_USER', 'إسناد موظّف/دور'), ('CREATE_GROUP', 'إنشاء عنقود'), ('EDIT_GROUP', 'تعديل عنقود'), ('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('LOGIN_FAILED', 'محاولة دخول فاشلة'), ('CREATE_BOOK', 'إنشاء كتاب'), ('EDIT_BOOK', 'تعديل كتاب'), ('DELETE_BOOK', 'حذف كتاب'), ('BACKUP_DATA', 'نسخ احتياطي'), ('SCANNER', 'استخدام السكانر')], max_length=50, verbose_name='الإجراء'),
        ),
    ]
