# Generated by Django 4.2.14 on 2026-09-01 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0074_entity_kind_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(choices=[('dept_head', 'رئيس القسم'), ('manager', 'المدير'), ('delegate', 'مفوَّض')], max_length=16, verbose_name='الصفة')),
                ('signed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت التوقيع')),
                ('digest', models.CharField(db_index=True, max_length=64, verbose_name='بصمة الملفّ')),
                ('verify_token', models.CharField(max_length=32, unique=True, verbose_name='رمز التحقّق')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظة')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='أُبطل في')),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='سبب الإبطال')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='core.book', verbose_name='الكتاب')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_signatures', to=settings.AUTH_USER_MODEL)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_signatures', to=settings.AUTH_USER_MODEL, verbose_name='الموقِّع')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='core.attachmentversion', verbose_name='النسخة الموقَّعة')),
            ],
            options={
                'verbose_name': 'توقيع',
                'verbose_name_plural': 'التواقيع',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['book', '-signed_at'], name='signature_book_time_idx')],
            },
        ),
    ]
