# Generated by Django 4.2.14 on 2026-09-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_signature_history_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhistory',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('edit', 'تعديل'), ('update_notes', 'تحديث ملاحظات'), ('status', 'تغيير الحالة'), ('delete', 'حذف (soft)'), ('restore', 'استعادة'), ('overdue', 'تجاوز الاستحقاق'), ('attach', 'إرفاق ملف'), ('attach-fail', 'فشل إرفاق'), ('delete-attachment', 'حذف مرفق'), ('replace-attachment', 'استبدال مرفق'), ('restore-attachment', 'استعادة مرفق'), ('merge', 'دمج ملفات'), ('merge-pages', 'دمج صفحات'), ('remove-pages', 'إزالة صفحات'), ('link-added', 'ربط بكتاب'), ('link-removed', 'فكّ ربط'), ('referral', 'تفريق/إحالة'), ('referral-received', 'استلام الإحالة'), ('referral-done', 'إنجاز الإحالة'), ('referral-returned', 'إعادة الإحالة'), ('reminder', 'تنبيه'), ('custody', 'انتقال عهدة'), ('registered', 'قُيّد في دفتر قسم'), ('circular', 'تعميم على عنقود'), ('sign', 'توقيع مصادقة'), ('sign-revoked', 'إبطال توقيع'), ('archived', 'تمام أرشفة'), ('archive-reopened', 'فتح مؤرشف')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='custodyevent',
            name='event',
            field=models.CharField(choices=[('intake', 'قيدٌ في السجلّ'), ('unit_receipt', 'استلامُ وحدة'), ('archive_done', 'تمامُ أرشفة'), ('courier_pickup', 'تسليمٌ لمتعهّد البريد'), ('return', 'إعادة'), ('archive_reopen', 'فتحُ مؤرشَف')], db_index=True, max_length=20, verbose_name='الحدث'),
        ),
    ]
